AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: java11
    Timeout: 120
    MemorySize: 512

Parameters:
  stageName:
    Type: String
    Default: dev
    Description: Backend Service Stage
  secretName:
    Default: dev-rds
    Description: Database user and password secret name
    Type: String

Resources:
  restApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: halo-service-api-${stageName}
      StageName:
        Ref: stageName
      Auth:
        Authorizers:
          GeneralAuth:
            UserPoolArn:
              - arn:aws:cognito-idp:us-east-1:608236930044:userpool/us-east-1_SuntsKRjy
            Identity:
              Header: Authorization

  getCompaniesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: halo-service-get-companies-${stageName}
      CodeUri: .
      Handler: com.empirical.handlers.CompanyHandler::getCompanies
      Events:
        List:
          Type: Api
          Properties:
            Auth:
              Authorizer: GeneralAuth
            Path: /companies
            Method: GET
            RestApiId:
              Ref: restApi
      Environment:
        Variables:
          RDS_HOST: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:host}}'
          RDS_DB_NAME: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:dbname}}'
          RDS_USERNAME: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:username}}'
          RDS_PASSWORD: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:password}}'
          USER_POOL_ID: 'us-east-1_SuntsKRjy'
      VpcConfig:
        SecurityGroupIds:
          - sg-0cb09fef2335184e1
        SubnetIds:
          - subnet-05127700ea24fc9d1
          - subnet-0f8599f0deec73013
          - subnet-07c4974c6ac5bf3c4
          - subnet-09e88dc7be2a5dd2a
          - subnet-02aa226174e008cdc
          - subnet-09b34bba3881d30ef
      Role: !GetAtt role.Arn

  createCompanyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: halo-service-create-company-${stageName}
      CodeUri: .
      Handler: com.empirical.handlers.CompanyHandler::createCompany
      Events:
        List:
          Type: Api
          Properties:
            Auth:
              Authorizer: GeneralAuth
            Path: /companies
            Method: POST
            RestApiId:
              Ref: restApi
      Environment:
        Variables:
          RDS_HOST: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:host}}'
          RDS_DB_NAME: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:dbname}}'
          RDS_USERNAME: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:username}}'
          RDS_PASSWORD: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:password}}'
          USER_POOL_ID: 'us-east-1_SuntsKRjy'
      VpcConfig:
        SecurityGroupIds:
          - sg-0cb09fef2335184e1
        SubnetIds:
          - subnet-05127700ea24fc9d1
          - subnet-0f8599f0deec73013
          - subnet-07c4974c6ac5bf3c4
          - subnet-09e88dc7be2a5dd2a
          - subnet-02aa226174e008cdc
          - subnet-09b34bba3881d30ef
      Role: !GetAtt role.Arn

  createOwnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: halo-service-create-owner-${stageName}
      CodeUri: .
      Handler: com.empirical.handlers.OwnerHandler::createOwner
      Events:
        List:
          Type: Api
          Properties:
            Auth:
              Authorizer: GeneralAuth
            Path: /owners
            Method: POST
            RestApiId:
              Ref: restApi
      Environment:
        Variables:
          RDS_HOST: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:host}}'
          RDS_DB_NAME: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:dbname}}'
          RDS_USERNAME: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:username}}'
          RDS_PASSWORD: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:password}}'
          USER_POOL_ID: 'us-east-1_SuntsKRjy'
      VpcConfig:
        SecurityGroupIds:
          - sg-0cb09fef2335184e1
        SubnetIds:
          - subnet-05127700ea24fc9d1
          - subnet-0f8599f0deec73013
          - subnet-07c4974c6ac5bf3c4
          - subnet-09e88dc7be2a5dd2a
          - subnet-02aa226174e008cdc
          - subnet-09b34bba3881d30ef
      Role: !GetAtt role.Arn

  role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
      Policies:
        - PolicyName: rds-iamauth
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'rds-db:connect'
                Resource: '*'
      Path: /service-role/